Fix mount error message
This fixes a confusing error message that I hit:

mount: /tmp/fw: special device /dev/mmcblk01 does not exist.
Error: mount /dev/mmcblk02 /tmp/boot failed